### ISSUE TITLE
Does removing a file in a branch removes it from the master branch even before merging the two branches?

### ISSUE THREAD

**Issue by mohamedeliwa** [JacksonBates/fcc-git-nomic#16]
Sorry, 
I've another question.
After I forked this repo and cloned it on my local machine then made the new_ruleset branch out of the master branch.
I wanted to modify the new_ruleset branch by deleting the old RULES.md file. 
I already deleted it from the branch and committed the changes to the branch but not to the master branch.
And also I didn't merge the branch with master yet.
But the file is deleted from the master branch, could anyone tell me why ?
As when I `checkout` to the master branch and do `ls -la`  command , I don't find the file.
What if I want to delete the branch and discard the changes made to it ?
And what if I want to delete a file from a branch but not from the master branch what commands should I use?

**Comment by JacksonBates** [comment]
> But the file is deleted from the master branch, could anyone tell me why?

As far as I'm aware, that shouldn't happen. 

I just tested it locally to confirm, and it doesn't. Without realising, maybe you deleted from master?

**Comment by mohamedeliwa** [comment]
Yes, you're right thanks :)
