### ISSUE TITLE
Add "How to vote" file

### ISSUE THREAD

**Issue by mikagrubinen** [JacksonBates/fcc-git-nomic#18]
I am new to the game and in order to create a pull request I had to vote for open pull requests first. It took some time until I figured it out how to vote. There is probably going to be a new way of voting (with +1), so I thought it would be a good idea to create new file "How to vote". The new file would include explanations and a couple of screenshots like this..

![screen shot 2018-11-21 at 9 42 18 pm](https://user-images.githubusercontent.com/7894346/48884221-4ae46100-edd8-11e8-910c-ddade0869c4c.png)

If you don't like the idea of adding new file than something similar can be added to wiki. Please let me know what you think.

**Comment by JacksonBates** [comment]
This is a good idea!

I'm happy for it to be it's own file, added to the CONTRIBUTORS.md, or added to the wiki - they are all decent options.

I think as long as the CONTRIBUTING.md (and maybe the README.md) also has a link to it if it is elsewhere, then the actual format could be anything.

@mikagrubinen would you like to make this?

**Comment by mikagrubinen** [comment]
Yes, no problem. I'll make it in next couple of day probably.
