### ISSUE TITLE
Delete Local and Remote Branch After the PR is Accepted or Closed, not Before

### ISSUE THREAD

**Issue by camper-fcc** [JacksonBates/fcc-git-nomic#3]
After opening a pull request, the next step in [CONTRIBUTING.md](https://github.com/JacksonBates/fcc-git-nomic/blob/master/CONTRIBUTING.md) leads the player to potentially delete their branch too soon:

> Now you can delete your local and remote branches:

It's possible more work will need to be done on that branch and deleting it might cause problems with this process.

Language should be added that reminds the player to not delete the local and remote branches until the PR has either been accepted or closed.

**Comment by JacksonBates** [comment]
Very good suggestion! I'll make the fix.
